### ISSUE TITLE
How to paginate an array within a document

### ISSUE THREAD

**Issue by simararneja** [mixmaxhq/mongo-cursor-pagination#120]
Let's say i want to fetch a document by `_id` and want to paginate `names` field to retrieve only first two name objects

Document as below - 

```json

{
"_id": "1",
"names": [
   {
      "id": "344",
     "name": "A"
   }, 
  {
      "id": "144",
      "name": "B"
  },
  {
      "id": "244",
      "name": "C"
  },
  {
      "id": "444",
      "name": "D"
  }]
}

```

Expected output -  Should also include `hasNext`, `hasPrevious` accordingly 

```json

{
"_id": "1",
"names": [
   {
      "id": "344",
     "name": "A"
   }, 
  {
      "id": "144",
      "name": "B"
  }]
}

```

**Comment by simararneja** [comment]
@skeggse Does this library support such pagination ?

**Comment by simararneja** [comment]
Inactive community. Closing this

**Comment by bradvogel** [comment]
Sorry for the delay. This library doesn't support paging within a single document. It only supports paging at the collection level.
