### ISSUE TITLE
I'm a bit confused over the generateCursorQuery expected params next / previous

### ISSUE THREAD

**Issue by chanced** [mixmaxhq/mongo-cursor-pagination#128]
https://github.com/mixmaxhq/mongo-cursor-pagination/blob/fcdbd7ca799952ca6f5ba030270de3ac0e9ca57b/src/utils/query.js#L79-L122

The docs say that next / previous should be a string and they are being fetched from the params here: 
https://github.com/mixmaxhq/mongo-cursor-pagination/blob/fcdbd7ca799952ca6f5ba030270de3ac0e9ca57b/src/utils/query.js#L95

but then they are being treated as an array here:

https://github.com/mixmaxhq/mongo-cursor-pagination/blob/fcdbd7ca799952ca6f5ba030270de3ac0e9ca57b/src/utils/query.js#L102
https://github.com/mixmaxhq/mongo-cursor-pagination/blob/fcdbd7ca799952ca6f5ba030270de3ac0e9ca57b/src/utils/query.js#L107

Also, is there a reason why an `$or` is performed on`$lt`/`$gt` and `$eq` over using `$gte` / `$lte`?

Thank you!

**Comment by bradvogel** [comment]
On the first question - `params` is passed through `sanitizeParams` here which converts `params.next` and `params.previous` into an array:  https://github.com/mixmaxhq/mongo-cursor-pagination/blob/fcdbd7ca799952ca6f5ba030270de3ac0e9ca57b/src/find.js#L32

On the second question - it's to handle an edge case. Comment out lines https://github.com/mixmaxhq/mongo-cursor-pagination/blob/fcdbd7ca799952ca6f5ba030270de3ac0e9ca57b/src/utils/query.js#L105-L112 and run `npm test` locally to see this edge case (explained by the unit test that exercises it).

**Comment by chanced** [comment]
Ahh, thanks! I appreciate it. I completely missed  `params = _.defaults(await sanitizeParams(collection, params), { query: {} }); ` somehow.
