### ISSUE TITLE
Question: support for multiple sorters?

### ISSUE THREAD

**Issue by Pavel910** [mixmaxhq/mongo-cursor-pagination#150]
I was wondering if you have any advice on how to approach handling multiple sorters?
So far in the code I can only see support for 1 secondary sorter and I'm trying to wrap my brain around how to support multiple sorters, like, `{ price: -1, name: 1 }` and so on.

Is it even possible? So far I can't seem to achieve this due to the sort field being used in the query `$or`, and so it filters our the records based on all sort field values.

Any advice is greatly appreciated! Cheers!

**Comment by bradvogel** [comment]
Great question. This library doesn't support multiple sort params today. PRs welcome!
