### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by NoahHahm** [mixmaxhq/mongo-cursor-pagination#161]
first, thank you for the great open source.
we decided to use mixmax cursor as a way to fetch large amounts of data through mongodb.
It is also burdensome to request paging to db every time.
I'm trying to cache the paging itself with 'next' field key as the redis key value, but I would like to know if there is any problem.

**Comment by bradvogel** [comment]
This should work. The cursor returned in the 'next' field should be durable in that you can store it and re-query later.
