### ISSUE TITLE
Support collection object from official mongodb driver

### ISSUE THREAD

**Issue by vladgolubev** [mixmaxhq/mongo-cursor-pagination#19]
Hi,

thanks for the package. What do you think about supporting official mongodb driver collection object? If you agree from the lib design standpoint I can help w/ implementation.

Thanks

**Comment by ghmeier** [comment]
Hi @vladgolubev, while the current `6.0.0` release doesn't support the mongodb collection, the `5.0.0` release supports it with the exact same features.

**Comment by mathieug** [comment]
Hi @ghmeier / @bradvogel 
What if you have to do a fix on the pagination?
I think you did an amazing work here, the package should support the official mongodb driver and why not a package for mongoose, mongoist, ... with mongo-cursor-pagination in peerDependency?

**Comment by ghmeier** [comment]
Yeah that's a good point. At this point we made the decision to move forward assuming a collection object the supports the `mongoist` API to keep the internals of this library simple. 

If you're interested in supporting multiple mongo drivers, we'd definitely consider merging a proposed PR 👍
