### ISSUE TITLE
[Feature Proposal] return count of matched documents in response

### ISSUE THREAD

**Issue by nathanielrindlaub** [mixmaxhq/mongo-cursor-pagination#253]
It would be fantastic to know from how many documents match the query in the collection (sans limit) when you get a response.

**Comment by christoph-findling** [comment]
+1

**Comment by bradvogel** [comment]
I'm not sure this is in scope of this library, as this library is intended to avoid the performance hazard of pulling the total number of records that match the query.

Would querying the count using this pattern work for you?

```
const query = { color: 'blue' };
const [firstPageResults, totalCount] = await Promise.all([
  MongoPaging.find(db.collection('myobjects'), {
    query,
    limit: 2,
  }),
  db.collection('myobjects').count(query)
]);
```

**Comment by christoph-findling** [comment]
That'll do, thanks a bunch!
