### ISSUE TITLE
previous and next params

### ISSUE THREAD

**Issue by andreiaiova** [mixmaxhq/mongo-cursor-pagination#27]
I am trying to do a pagination server side with mongo-cursor-pagination but the problem is that the pagination works only when i click on next button ( I send limit, next, previous) and not when i click on previous button. Also if go on page 3 from page 1 is not working because is showing the content from page 2. Please let me know how to make the call from frontend to get the content right from every page. This is my server side code:

router.get('/',(req, res, next) => {

    var result = MongoPaging.find(db.collection('items'), {
      limit: parseInt(req.query.limit), // Also need to cap this to 25
      next: req.query.next,
      previous: req.query.previous,
    });
    result.then(function(data) {
      data.count = 100;
      res.status(200).json(data);
    }).catch(function(err) {
      res.status(401).send({error: "Error at get items"});
    });
});

**Comment by bardiel** [comment]
You have to set either `next` **OR** `previous`. See: https://github.com/mixmaxhq/mongo-cursor-pagination/blob/master/src/find.js#L65

You could check whether `req.query` has `next` or `previous` and then build the params argument.

(also, your client app should send either `next` or `previous`)

**Comment by andreiaiova** [comment]
I have an issue now.For example when I go from page 2 to page 3 its working but if I want to go from page 2 to page 6 then the result that is showed is from page 3.

**Comment by bardiel** [comment]
I don't seem to understand... The `next` and `previous` params aren't the page number, but the cursor returned by the previous query.
You can achive offset-based pagination directly with mongodb.

**Comment by andreiaiova** [comment]
I know the next and previous params aren't the page number but what I want to say is that the pagination now work fine if I go from page 1 to page 2 not when I go to a page with higher difference than one step because it only return me the next page.How should I set the next and previous params to get the correct data for page 6 for example if I am on the page 1 (so the pagination works good when I go to page 2 from page 1, not if I go at the page 5 from page 1 --this is only an example).

**Comment by bardiel** [comment]
Oh, I get what you're saying.
Since the `next` and `previous` tokens are based on the current query, I'm not quite sure it's even possible to jump pages without cycling through every intermediate query...

**Comment by bradvogel** [comment]
Correct - you can't jump pages. This module is only for "cursor-based" paging, as described by blog post https://mixmax.com/blog/api-paging-built-the-right-way. If you need to skip pages, you'll have to use a different library for implement your own solution using Mongo's skip().
