### ISSUE TITLE
sort and limit queries in aggregate are sliced instead of pushed

### ISSUE THREAD

**Issue by thedarkrai07** [mixmaxhq/mongo-cursor-pagination#317]
The $sort and $limit are sliced between the aggregate array rather than pushed in the end. This leads to abnormal behaviour while using aggregate. 

@leamarty Are you open to fixing it? I can share a PR.

**Comment by leamarty** [comment]
Hi @thedarkrai07 ! Please share the PR if you already have it in place. Thanks for contributing!

**Comment by thedarkrai07** [comment]
Hey @leamarty, I have created the PR. I was not able to increase test coverage as the test cases are already failing. However, I have tested it with a project of mine and it works fine :)

**Comment by raphaelbs** [comment]
Solved by https://github.com/mixmaxhq/mongo-cursor-pagination/pull/323.
Version [v7.8.0](https://github.com/mixmaxhq/mongo-cursor-pagination/releases/tag/v7.8.0) supports it.
