### ISSUE TITLE
base64-url 1.3.2 has a vulnerability.

### ISSUE THREAD

**Issue by pwiebe** [mixmaxhq/mongo-cursor-pagination#33]
Should upgrade base64-url to version >=2.0.0 as per https://nodesecurity.io/advisories/660.

**Comment by bradvogel** [comment]
Yes, we should. Will accept a PR :)

**Comment by pwiebe** [comment]
PR https://github.com/mixmaxhq/mongo-cursor-pagination/pull/41 addresses this.

**Comment by ttacon** [comment]
Just released 7.0.1 (which contains #41) to address this.
