### ISSUE TITLE
MongoDB Collation

### ISSUE THREAD

**Issue by limianwang** [mixmaxhq/mongo-cursor-pagination#52]
I was wondering if there's an intended support for collation when doing `find`?

ref: https://docs.mongodb.com/manual/reference/collation/

I forked this repository and did something like this:

```
diff --git a/src/find.js b/src/find.js
index 886d310..84e15ac 100644
--- a/src/find.js
+++ b/src/find.js
@@ -40,6 +40,7 @@ module.exports = async function(collection, params) {
   const findMethod = collection.findAsCursor ? 'findAsCursor': 'find';

   const results = await collection[findMethod]({ $and: [cursorQuery, params.query] }, params.fields)
+    .collation({ strength: 1, locale: 'en' })
     .sort($sort)
     .limit(params.limit + 1) // Query one more element to see if there's another page.
     .toArray();
```

Is this a feature you guys are intending to support down the road?

Thanks!

**Comment by raphaelbs** [comment]
Collation is fully supported from [v7.7.0](https://github.com/mixmaxhq/mongo-cursor-pagination/releases/tag/v7.7.0) onward.
You can check the docs here: https://github.com/mixmaxhq/mongo-cursor-pagination#-important-note-regarding-collation-
